### ISSUE TITLE
FR: resize to avoid overlap

### ISSUE THREAD

**Issue by Offbeatmammal** [snorpey/circlepacker#10]
I'm trying to find a circle packing solution to use with ChartJS - which has a handy Bubble chart which takes x,y, and radius, but doesn't have a packing/treemap type solution.

really like this library as it handles a center of gravity which I think is a really elegant way to make layouts look nice, but doing some quick testing with the static sample (before even using it to feed into ChartJS) I notice adding circles it starts to visually overlap. Is it possible to configure it to apply a scale factor to all the radii to avoid overlap while ensuring fit into the bounds? Alternative would be to get a flag in the returned packer object to alert to their being overlaps and I could rescale the radii and re-run

In my specific scenario I'd know all the radii to start with, and happy to wait for a few passes of the calcs before rendering the chart

(of course my ideal dream would be to have this packing algo implemented as a ChartJS chart type that I just give a list of 'raw' radii to and it calculates the x,y, and scaled-radii by magic!)

**Comment by snorpey** [comment]
Hey @Offbeatmammal thank you for your interest in this library.

Could you share a code sample that shows your problem? I think that would help me understand the issue better.

Thank you!

**Comment by Offbeatmammal** [comment]
using the static.html from the sample here, if I hit 'add circle' a few times I end up with something like this where you'll see an overlapping circle.
<img width="318" alt="Screenshot 2023-08-14 at 8 14 04 pm" src="https://github.com/snorpey/circlepacker/assets/677594/1d062ba5-1439-4c0f-96c0-7a3fe5fb2a0a">

for my specific use case I'd be getting a list of radii that correspond the the data points in my valueset (between 10 and 20 items, with radius values ranging from 1 to around 250) and using this to give me a layout

what I'd love to happen in that scenario is either:
- to get a response that it's not been able to fit everything with no collisions, so to fit in the given space I need to reduce the radii on all the circles and try again
- better (because I'm lazy!) would be an automatic re-scale of the radii where the packer object I get back gives me the x,y, original radius and scaled radius for each point

once I have the list of fitted x, y, and radius for each of the points, I'd pass that as the dataset into a [ChartJS bubble chart](https://www.chartjs.org/docs/latest/charts/bubble.html) for display

I know some libraries like D3 do have a circlepacking solution but [no out-of-the-box solution for chartjs (yet!)](https://www.chartjs.org/docs/latest/developers/charts.html)

**Comment by snorpey** [comment]
hey @Offbeatmammal sorry for taking such a long time to reply.

It looks like didn't get an email notification. for your answer. I'm still looking into this problem, and hopefully I can come up with a solution that works for you. In the meantime, a super hacky solution might be to increase the number of centering passes by a lot. This doesn't make the problem go away, but to me it seems that intersections happen less often.

**Comment by snorpey** [comment]
hey @Offbeatmammal i just updated the code:

it is now possible to pass a `correctionPasses` parameter, which adds additional calculations each frame to avoid overlapping circles. 

In addition to that, it is now also possible to get information about overlapping circles by passing `calculateOverlap: true`.
I also added a `pack` function that works as a shorthand for using `continuousMode: false`;

it should now be possible to do something like this:

```javascript
import { pack } from 'circlepacker';

const { updatedCircles, overlappingCircles } = await pack({
	circles,
	bounds,
	target,
	calculateOverlap: true,
	correctionPasses: 20,
});
```

Let me know if this helps or if you have any questions.

**Comment by Offbeatmammal** [comment]
the correctionPasses seems to help with reducing how often I'm seeing overlapping, so reduces the problem, and then overlappingCircles is great, as if that's set I know I need to go back and scale down the radii (experimenting with the overlapDistance to find the best scale factor for the first pass attempt). Huge help, thanks
