### ISSUE TITLE
[Feature Request] Add option to "addCircle" to lock certain circles in place

### ISSUE THREAD

**Issue by marciot** [snorpey/circlepacker#2]
I am using circlepacker in my project and it would be great if there was a way to lock certain circles in place, so that those circles remained stationary, but the other circles would position themselves around the locked circles.

**Comment by snorpey** [comment]
hey @marciot thank you for the interest in this project!

this is a great idea so i just pushed a [new version](https://github.com/snorpey/circlepacker/releases/tag/v1.1.1) of circlepacker that includes this feature (look for the `pinCircle()` and `unpinCircle()` methods).

let me know if it works for you or if you have any questions. have a great day!

**Comment by marciot** [comment]
Wow! This was super fast! I'll try it out tomorrow! I actually "cheated" and got the effect I wanted by registering the object I wanted to stay locked with the drag handler, but pin and unpin makes a lot more sense!

BTW, I do not know if you are familiar with 3D printing, but I am using your library in the following slicing program which will be unveiled to the public shortly! The idea is that if you place multiple objects, it uses the circle packer to keep them from overlapping on the print surface.

https://syndaverco.github.io/slicer
