### ISSUE TITLE
[Feature Request] Ability to modify circle radius

### ISSUE THREAD

**Issue by thomas-dm** [snorpey/circlepacker#4]
Hello there, and thanks for this nifty little package!

I’m playing around with your lib and I’m really enjoying its simplicity and small size. I’m even considering using it for a small dataviz! However, as far as I can tell, there’s currently no way to modify a circle’s radius after it’s been pushed to the packer. This would be a really useful feature to show data changes and to add a little animation if needed! 

Thanks again! 👍

**Comment by snorpey** [comment]
hey @thomas-dm thank you for your interest in this project and your suggestion. i think it's a great idea and, i'll get started with the implementation it right away. sorry for taking such a long time to respond to your request.

**Comment by snorpey** [comment]
@thomas-dm i just published version [1.1.3](https://github.com/snorpey/circlepacker/releases/tag/v1.1.3). have a look at the [`setCircleradius()`](https://github.com/snorpey/circlepacker#setcircleradiuscircleid-number) method. let me know if you have any questions. thanks again for your feedback!

**Comment by thomas-dm** [comment]
Thanks for the update!
Before you responded to the issue, I actually ended writing a custom packer to meet the specific needs of the project I’m working on. But I just took a look at the update, and this is a really nice new feature to have indeed! 👍
