### ISSUE TITLE
StopLoop incorrectly updates listeners

### ISSUE THREAD

**Issue by dustinlacewell** [snorpey/circlepacker#5]
In stopLoop you have `this.updateListeners( 'moveend' );` but that method takes an object with properties.

This causes the moveend listeners to never be called.

**Comment by snorpey** [comment]
hey @dustinlacewell ,
thank you for your interest in the project and for pointing out this issue.

i just published version [1.1.4](https://github.com/snorpey/circlepacker/releases/tag/v1.1.4) of this library that should fix this issue.

let me know if this works for you.

thanks again!
