### ISSUE TITLE
How to import the library in NodeJS project?

### ISSUE THREAD

**Issue by sadespresso** [snorpey/circlepacker#52]
I'm using the library through `npm`, with TypeScript, and I'm having a little hard time importing and using it in my code.

I have tried below with VS Code, TypeScript 4 and 5. Also tried in plain node project, and SvelteKit project I'm currently working on.

```typescript
// Suggested by LSP, doesn't work
import { CirclePacker } from 'CirclePacker';
// Suggested by LSP, doesn't work
import type PackedCircle from 'PackedCircle';

// LSP doesn't recognize "circlepacker"
import { CirclePacker } from "circlepacker";
```

Thank you!

**Comment by snorpey** [comment]
hey @sadespresso thank you for your interest in the project and for filing this issue. it looks like there was indeed an issue with the typescript types when installing from npm.

i just published version `2.0.7` to npm that includes the correct path to the type definitions. please let me know if this fixes your issue.

thank you!

**Comment by sadespresso** [comment]
Thank you for the quick response 😊

**Comment by sadespresso** [comment]
Hello there! I have tried the updated version of the package. The type definitions seem to be working. However, when constructing `CirclePacker`, there is one slight problem.

Working properly, but TypeScript expects `x` and `y` to be immediate child of the object rather than `position`'s.
```typescript
new CirclePacker({
  circles: [
    {
      position: {
        x: 0,
        y: 0,
      },
      id: "id",
      radius: 50.0,
    },
  ],
});
```

No type errors, but throws `Can't add circles: some of the items are not well formatted.`
```typescript
new CirclePacker({
  circles: [
    {
      x: 0,
      y: 0,
      id: "id",
      radius: 50.0,
    },
  ],
});

```

**Comment by snorpey** [comment]
hey @sadespresso,
it looks like you spotted another issue in the code 😅 i should probably add more typescript examples and tests at some point…
i just published version `2.1.0` that hopefully fixes your issue.
be aware that i had to change some of the parameters for `CirclePacker`, specifically `noWorker` and `animationLoop`.

**Comment by sadespresso** [comment]
Thank you for making fixes so quickly!

Type issues seem to be fixed. But there are minor ones like `CircleID` type cannot be imported, but somehow works when I do `import { CirclePacker } from "circlepacker"`.

**Comment by sadespresso** [comment]
I think the issue has been resolved, thanks again :))

**Comment by sadespresso** [comment]
I think rewriting this in TS and using something like `tsup` would be less complicated. Just a suggestion
