### ISSUE TITLE
Calling setTarget repeatedly causes loop to stop prematurely

### ISSUE THREAD

**Issue by chickenwing** [snorpey/circlepacker#6]
I noticed that calling setTarget repeatedly (with different x, y values) causes the animation loop to stop prematurely. The stopLoop method seems to be called too early.

Calling updateLoop or startLoop when this happens moves the circles one frame in the right 'direction' before calling stopLoop again prematurely.

Hope this description is enough to locate the bug. If not I will supply a bug demo.

Thank you!

**Comment by snorpey** [comment]
hey @chickenwing, thank you for reporting this bug! did you close this issue intentionally or does the bug still exist? I will have a look at the code throughout the next couple of days and try to reproduce the issue.

**Comment by chickenwing** [comment]
Was closing because I thought I was doing something wrong. But I think I know the issue now.

I made a bug demo at: https://js-khse8x.stackblitz.io/ (source at https://stackblitz.com/edit/js-khse8x?file=index.js)
Click on the 'shift target' button. Sometimes you have to click it repeatedly or wait for the previous animation to completely stop or click 'random target' before.
It will sometimes not complete the circle movements. They will abruptly stop.

I think this is because setTarget inside shiftTarget only modifies the x value. Thus the hasItemMoved function inside CirclePacker.js returns false even though movement still happens along the x axis.

I fixed it by changing
`				Math.abs(positions[id].delta.x) > 0.005 &&
				Math.abs(positions[id].delta.y) > 0.005`
to
`				Math.abs(positions[id].delta.x) > 0.005 ||
				Math.abs(positions[id].delta.y) > 0.005`

inside the hasItemMoved function. Makes more sense to me like this for now. But I am not sure if this has other unwanted consequences somewhere else?

Thank you for looking into this!

**Comment by snorpey** [comment]
@chickenwing thank you for taking the time to create a demo and for proposing a fix! i just published version 1.1.5 that includes your proposed fix.
