### ISSUE TITLE
Execution environment

### ISSUE THREAD

**Issue by Irrelon** [snorpey/circlepacker#9]
Hey there!

I notice you mentioned it executes in a webworker. Is there a mode to support functionality outside of a browser-based worker and execute the algoritm via Node.js for instance? On the server-side, the execution of the process doesn't need to be async (and if it does, we can kick off another process to do this).

**Comment by Irrelon** [comment]
Ignore me, I've looked through the implementation and the functional algorith, part is separately defined from the web worker part so nicely abstracted and not tied together. Anyone else reading this, the implementation supports execution outside of a web worker.

**Comment by snorpey** [comment]
FYI @Irrelon (and anyone else reading this):

i just updated the code and it is now possible to pass `{useWorker: false}` to execute the code directly in the main thread, without using a worker.

**Comment by Irrelon** [comment]
Nice one :) 👍🏻
